// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace TaxpayerLibraryEntityVersion.Models
{
    public partial class Taxpayer
    {
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string FullName => $"{FirstName} {LastName}";
        public string SSN { get; set; }
        public string SocialSecurityNumber => SSN.Insert(5, "-").Insert(3, "-");
        public string Pin { get; set; }
        public DateTime? StartDate { get; set; }
        public int CategoryId { get; set; }
        public Category Category { get; set; }
        public override string ToString() => $"{FirstName} {LastName}";
    }

    public class Category
    {
        [Key]
        public int CategoryId { get; set; }
        public string Description { get; set; }
        public List<Taxpayer> Books { get; set; }

        public Category()
        {
            Books = new List<Taxpayer>();
        }
    }
}